[package]
name = "lilnouns-bots"
version = "1.0.0-alpha.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = { version = "0.13.0", features = ["reqwest"] }
serde = "1.0.188"
reqwest = "0.11.20"
tokio = { version = "1.32.0", features = ["full"] }
anyhow = "1.0.75"
sled = "0.34.7"
lazy_static = "1.4.0"
log = "0.4.20"
env_logger = "0.10.0"
serde_json = "1.0.106"
futures = "0.3.28"
clap = { version = "4.4.3", features = ["derive"] }
serenity = "0.11.6"
