[package]
name = "lilnouns-bots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = { version = "0.13.0", features = ["reqwest"] }
serde = "1.0.188"
reqwest = "0.11.20"
anyhow = "1.0.75"
