[package]
name = "lilnouns-bots"
version = "1.0.0-alpha.17"
edition = "2021"
include = ["*.graphql"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
cfg-if = "1.0.0"
chrono = "0.4.31"
console_error_panic_hook = { version = "0.1.7", optional = true }
graphql_client = { version = "0.13.0", features = ["reqwest"] }
log = "0.4.20"
reqwest = "0.11.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
worker = "0.0.18"
worker_logger = { version = "0.2.0", features = ["color"] }

[profile.release]
lto = true
strip = true
codegen-units = 1
