[package]
name = "lilnouns-bots"
version = "1.0.0-alpha.7"
edition = "2021"
include = ["*.graphql"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
graphql_client = { version = "0.13.0", features = ["reqwest"] }
serde = { version = "1.0.188", features = ["derive"] }
reqwest = "0.11.20"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.75"
lazy_static = "1.4.0"
log = "0.4.20"
env_logger = "0.10.0"
serde_json = "1.0.107"
futures = "0.3.28"
clap = { version = "4.4.4", features = ["derive"] }
serenity = { version = "0.11.6", default-features = false, features = ["rustls_backend", "model"] }
html2md = "0.2.14"
chrono = "0.4.31"
worker = "0.0.18"
getrandom = { version = "0.2.10", features = ["js"] }

[profile.release]
lto = true
strip = true
codegen-units = 1
