name = "lilnouns-bots"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

workers_dev = false
logpush = true
usage_model = "unbound"

[build]
command = "cargo install -q -f worker-build && worker-build --release"

[triggers]
crons = ["*/5 * * * *"]

[env.dev]

[[env.dev.kv_namespaces]]
binding = "LIL_NOUNS_BOTS"
id = "c193c4943cd5475196cd5bdd3298a8ff"

[env.dev.vars]
KV_STORE_NAME = "LIL_NOUNS_BOTS"
PROP_HOUSE_BASE_URL = "https://prop.house/lil-nouns"
PROP_HOUSE_COMMUNITY_ID = 2
PROP_HOUSE_GRAPHQL_URL = "https://prod.backend.prop.house/graphql"
PROP_LOT_BASE_URL = "https://lilnouns.proplot.wtf"
PROP_LOT_GRAPHQL_URL = "https://lilnouns.proplot.wtf/api/graphql"
ETHEREUM_MAINNET_RPC_URL = "https://eth.llamarpc.com"
