# Project Identification
name = "lilnouns-bots"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

# Worker Settings
workers_dev = false
logpush = true
usage_model = "unbound"

# Build Settings
[build]
command = "cargo install -q -f worker-build && worker-build --release"

# Trigger Settings
[triggers]
crons = ["*/5 * * * *"]

# Default KV Namespace
[[kv_namespaces]]
binding = "CACHE"
id = "6456908fdbcf4ce1b89b3028a5bbbe87"

# Global Variables
[vars]
# Ethereum Settings
ETHEREUM_MAINNET_RPC_URL = "https://eth.llamarpc.com"

# Link Generator Settings
LINK_GENERATOR_ENDPOINT = "https://lilnouns.click"

# Lil Nouns Settings
LIL_NOUNS_ENABLED = "false"
LIL_NOUNS_DISCORD_ENABLED = "true"
LIL_NOUNS_FARCASTER_ENABLED = "false"
LIL_NOUNS_BASE_URL = "https://lilnouns.wtf/vote"
LIL_NOUNS_GRAPHQL_URL = "https://api.goldsky.com/api/public/project_cldjvjgtylso13swq3dre13sf/subgraphs/lil-nouns-subgraph/1.0.4/gn"
LIL_NOUNS_WARP_CAST_CHANNEL = ""

# Meta Gov Settings
META_GOV_ENABLED = "false"
META_GOV_DISCORD_ENABLED = "true"
META_GOV_FARCASTER_ENABLED = "false"
META_GOV_BASE_URL = "https://lilnouns.wtf/vote/nounsdao"
META_GOV_SNAPSHOT_GRAPHQL_URL = "https://hub.snapshot.org/graphql"
META_GOV_SNAPSHOT_SPACE_ID = "leagueoflils.eth"
META_GOV_WARP_CAST_CHANNEL = ""

# Prop House Settings
PROP_HOUSE_ENABLED = "true"
PROP_HOUSE_DISCORD_ENABLED = "true"
PROP_HOUSE_FARCASTER_ENABLED = "false"
PROP_HOUSE_BASE_URL = "https://prop.house/lil-nouns"
PROP_HOUSE_COMMUNITY_ID = "2"
PROP_HOUSE_GRAPHQL_URL = "https://prod.backend.prop.house/graphql"
PROP_HOUSE_WARP_CAST_CHANNEL = ""

# Prop Lot Settings
PROP_LOT_ENABLED = "true"
PROP_LOT_DISCORD_ENABLED = "true"
PROP_LOT_FARCASTER_ENABLED = "false"
PROP_LOT_BASE_URL = "https://lilnouns.proplot.wtf"
PROP_LOT_GRAPHQL_URL = "https://lilnouns.proplot.wtf/api/graphql"
PROP_LOT_WARP_CAST_CHANNEL = ""

# KV Store Settings
KV_STORE_NAME = "CACHE"

# Environment: Development
[env.dev]

# KV Namespaces for Development
[[env.dev.kv_namespaces]]
binding = "CACHE"
id = "c193c4943cd5475196cd5bdd3298a8ff"

# Variables for Development
[env.dev.vars]
# Ethereum Settings
ETHEREUM_MAINNET_RPC_URL = "https://eth.llamarpc.com"

# Link Generator Settings
LINK_GENERATOR_ENDPOINT = "https://lilnouns.click"

# Lil Nouns Settings
LIL_NOUNS_ENABLED = "true"
LIL_NOUNS_DISCORD_ENABLED = "true"
LIL_NOUNS_FARCASTER_ENABLED = "true"
LIL_NOUNS_BASE_URL = "https://lilnouns.wtf/vote"
LIL_NOUNS_GRAPHQL_URL = "https://api.goldsky.com/api/public/project_cldjvjgtylso13swq3dre13sf/subgraphs/lil-nouns-subgraph/1.0.4/gn"
LIL_NOUNS_WARP_CAST_CHANNEL = ""

# Meta Gov Settings
META_GOV_ENABLED = "true"
META_GOV_DISCORD_ENABLED = "true"
META_GOV_FARCASTER_ENABLED = "true"
META_GOV_BASE_URL = "https://lilnouns.wtf/vote/nounsdao"
META_GOV_SNAPSHOT_GRAPHQL_URL = "https://hub.snapshot.org/graphql"
META_GOV_SNAPSHOT_SPACE_ID = "leagueoflils.eth"
META_GOV_WARP_CAST_CHANNEL = ""

# Prop House Settings
PROP_HOUSE_ENABLED = "true"
PROP_HOUSE_DISCORD_ENABLED = "true"
PROP_HOUSE_FARCASTER_ENABLED = "true"
PROP_HOUSE_BASE_URL = "https://prop.house/lil-nouns"
PROP_HOUSE_COMMUNITY_ID = "2"
PROP_HOUSE_GRAPHQL_URL = "https://prod.backend.prop.house/graphql"
PROP_HOUSE_WARP_CAST_CHANNEL = ""

# Prop Lot Settings
PROP_LOT_ENABLED = "true"
PROP_LOT_DISCORD_ENABLED = "true"
PROP_LOT_FARCASTER_ENABLED = "true"
PROP_LOT_BASE_URL = "https://lilnouns.proplot.wtf"
PROP_LOT_GRAPHQL_URL = "https://lilnouns.proplot.wtf/api/graphql"
PROP_LOT_WARP_CAST_CHANNEL = ""

# KV Store Settings
KV_STORE_NAME = "CACHE"

# Analytics Engine Datasets for Development
[[env.dev.analytics_engine_datasets]]
binding = "METRICS"
